# Generated by Django 4.2.7 on 2025-05-26 16:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("farm_name", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mango_tree_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "farm_size_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stocking_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trees per hectare",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "surveillance_frequency_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Default surveillance interval in days"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "irrigation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="mango_pests_app.grower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MangoThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                (
                    "image",
                    models.CharField(default="default-threat.png", max_length=255),
                ),
                (
                    "threat_type",
                    models.CharField(
                        choices=[("pest", "Pest"), ("disease", "Disease")],
                        max_length=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seasonal_peak_months",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Dec-Mar' or 'Year-round'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "surveillance_indicators",
                    models.TextField(
                        blank=True,
                        help_text="What to look for during surveillance",
                        null=True,
                    ),
                ),
                (
                    "detection_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("difficult", "Difficult"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MangoTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tree_id", models.CharField(max_length=100, unique=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "variety",
                    models.CharField(
                        choices=[
                            ("kensington_pride", "Kensington Pride"),
                            ("calypso", "Calypso"),
                            ("honey_gold", "Honey Gold"),
                            ("r2e2", "R2E2"),
                            ("keitt", "Keitt"),
                            ("kent", "Kent"),
                            ("other", "Other"),
                        ],
                        default="kensington_pride",
                        max_length=50,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("young", "0-3 years"),
                            ("juvenile", "4-7 years"),
                            ("mature", "8-15 years"),
                            ("old", "16+ years"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "height_meters",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "canopy_diameter_meters",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mango_trees",
                        to="mango_pests_app.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "surveillance_priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority 1=Low, 5=Critical",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("frequency_days", models.PositiveIntegerField(default=14)),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveillance_plans",
                        to="mango_pests_app.grower",
                    ),
                ),
                ("locations", models.ManyToManyField(to="mango_pests_app.location")),
                (
                    "target_threats",
                    models.ManyToManyField(
                        blank=True, to="mango_pests_app.mangothreat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weather_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("trees_surveyed_count", models.PositiveIntegerField(default=0)),
                (
                    "total_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveillance_records",
                        to="mango_pests_app.grower",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mango_pests_app.location",
                    ),
                ),
                (
                    "surveillance_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mango_pests_app.surveillanceplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("none", "No Issues"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "inspection_time_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("findings", models.TextField(blank=True, null=True)),
                ("action_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("photo_taken", models.BooleanField(default=False)),
                (
                    "photo_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plant_parts_checked",
                    models.ManyToManyField(to="mango_pests_app.plantpart"),
                ),
                (
                    "surveillance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_inspections",
                        to="mango_pests_app.surveillancerecord",
                    ),
                ),
                (
                    "threats_found",
                    models.ManyToManyField(
                        blank=True, to="mango_pests_app.mangothreat"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="mango_pests_app.mangotree",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mangothreat",
            name="affected_plant_parts",
            field=models.ManyToManyField(blank=True, to="mango_pests_app.plantpart"),
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Found", "Found"),
                            ("Controlled", "Controlled"),
                            ("Escalated", "Escalated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=50,
                    ),
                ),
                ("findings", models.TextField(blank=True, null=True)),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mango_pests_app.disease",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mango_pests_app.pest",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="mango_pests_app.surveillancerecord",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mango_pests_app.mangothreat",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_inspections",
                        to="mango_pests_app.mangotree",
                    ),
                ),
            ],
        ),
    ]
