# Generated by Django 5.1.7 on 2025-05-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='farm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='mango_tree_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grower',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
