# Generated by Django 4.2.7 on 2025-05-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango_pests_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mangothreat",
            name="affected_plant_parts",
        ),
        migrations.RemoveField(
            model_name="mangothreat",
            name="detection_difficulty",
        ),
        migrations.RemoveField(
            model_name="mangothreat",
            name="seasonal_peak_months",
        ),
        migrations.RemoveField(
            model_name="mangothreat",
            name="surveillance_indicators",
        ),
        migrations.AlterField(
            model_name="mangothreat",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image of this threat",
                null=True,
                upload_to="threat_images/",
            ),
        ),
    ]
