# Generated by Django 4.2.7 on 2025-05-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango_pests_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspection",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="pest",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="record",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="threat",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="tree",
        ),
        migrations.AlterField(
            model_name="mangothreat",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="threat_images/"),
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="Inspection",
        ),
        migrations.DeleteModel(
            name="Pest",
        ),
    ]
