# Generated by Django 4.2.7 on 2025-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango_pests_app", "0002_remove_mangothreat_affected_plant_parts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantpart",
            options={"ordering": ["-surveillance_priority", "name"]},
        ),
        migrations.AddField(
            model_name="plantpart",
            name="time_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Multiplier for surveillance time",
                max_digits=3,
            ),
        ),
    ]
